project:
  title: "version_control_demo"

author: "John Little"
license: "CC BY-NC-SA 4.0"

editor: visual

output:
  html:
    self-contained: true
    toc: true
    output-dir: "reports"
    file: "index.html"